cloudpebble/cloudpebble/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cloudpebble.views.home', name='home'),
    # url(r'^cloudpebble/', include('cloudpebble.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
      url(r'^ide/', include('ide.urls', namespace='ide')),
      url(r'^accounts/', include('auth.urls')), # Namespacing this breaks things.
      url(r'^qr/', include('qr.urls', namespace='qr')),
      url(r'^$', include('root.urls', namespace='root')),
      url(r'', include('social.apps.django_app.urls', namespace='social')),
      url(r'^i18n/', include('django.conf.urls.i18n'))
)

cloudpebble/ide/urls.py
from django.conf.urls import patterns, url

from ide.api import proxy_keen, check_task, get_shortlink, heartbeat
from ide.api.git import github_push, github_pull, set_project_repo, create_project_repo
from ide.api.phone import ping_phone, check_phone, list_phones, update_phone
from ide.api.project import project_info, compile_project, last_build, build_history, build_log, create_project, \
    save_project_settings, save_project_dependencies, delete_project, begin_export, import_zip, import_github, do_import_gist, \
    get_projects
from ide.api.resource import create_resource, resource_info, delete_resource, update_resource, show_resource, \
    delete_variant
from ide.api.source import create_source_file, load_source_file, source_file_is_safe, save_source_file, \
    delete_source_file, rename_source_file
from ide.api.user import transition_accept, transition_export, transition_delete, whats_new
from ide.api.ycm import init_autocomplete
from ide.api.qemu import launch_emulator, generate_phone_token, handle_phone_token
from ide.api.npm import npm_search, npm_info
from ide.views.index import index
from ide.views.project import view_project, github_hook, build_status, import_gist, qemu_config, enter_phone_token
from ide.views.settings import settings_page, start_github_auth, remove_github_auth, complete_github_auth

urlpatterns = patterns(
    '',
    url(r'^$', index, name='index'),
    url(r'^import/github/(?P<github_account>.+?)/(?P<github_project>.+?)$', index, name='index'),
    url(r'^projects', get_projects, name='get_projects'),
    url(r'^project/create', create_project, name='create_project'),
    url(r'^project/(?P<project_id>\d+)$', view_project, name='project'),
    url(r'^project/(?P<project_id>\d+)/info', project_info, name='project_info'),
    url(r'^project/(?P<project_id>\d+)/save_settings', save_project_settings, name='save_project_settings'),
    url(r'^project/(?P<project_id>\d+)/save_dependencies', save_project_dependencies, name='save_project_dependencies'),
    url(r'^project/(?P<project_id>\d+)/delete', delete_project, name='delete_project'),
    url(r'^project/(?P<project_id>\d+)/create_source_file', create_source_file, name='create_source_file'),
    url(r'^project/(?P<project_id>\d+)/source/(?P<file_id>\d+)/load', load_source_file, name='load_source_file'),
    url(r'^project/(?P<project_id>\d+)/source/(?P<file_id>\d+)/save', save_source_file, name='save_source_file'),
    url(r'^project/(?P<project_id>\d+)/source/(?P<file_id>\d+)/rename', rename_source_file, name='rename_source_file'),
    url(r'^project/(?P<project_id>\d+)/source/(?P<file_id>\d+)/is_safe', source_file_is_safe, name='source_file_is_safe'),
    url(r'^project/(?P<project_id>\d+)/source/(?P<file_id>\d+)/delete', delete_source_file, name='delete_source_file'),
    url(r'^project/(?P<project_id>\d+)/create_resource', create_resource, name='create_resource'),
    url(r'^project/(?P<project_id>\d+)/resource/(?P<resource_id>\d+)/info', resource_info, name='resource_info'),
    url(r'^project/(?P<project_id>\d+)/resource/(?P<resource_id>\d+)/delete', delete_resource, name='delete_resource'),
    url(r'^project/(?P<project_id>\d+)/resource/(?P<resource_id>\d+)/update', update_resource, name='update_resource'),
    url(r'^project/(?P<project_id>\d+)/resource/(?P<resource_id>\d+)/(?P<variant>\d+(?:,\d+)*)/get', show_resource, name='show_resource'),
    url(r'^project/(?P<project_id>\d+)/resource/(?P<resource_id>\d+)/(?P<variant>\d+(?:,\d+)*)/delete', delete_variant, name='delete_variant'),
    url(r'^project/(?P<project_id>\d+)/build/run', compile_project, name='compile_project'),
    url(r'^project/(?P<project_id>\d+)/build/last', last_build, name='get_last_build'),
    url(r'^project/(?P<project_id>\d+)/build/history', build_history, name='get_build_history'),
    url(r'^project/(?P<project_id>\d+)/analytics', proxy_keen, name='proxy_analytics'),
    url(r'^project/(?P<project_id>\d+)/build/(?P<build_id>\d+)/log', build_log, name='get_build_log'),
    url(r'^project/(?P<project_id>\d+)/export', begin_export, name='begin_export'),
    url(r'^project/(?P<project_id>\d+)/github/repo$', set_project_repo, name='set_project_repo'),
    url(r'^project/(?P<project_id>\d+)/github/repo/create$', create_project_repo, name='create_project_repo'),
    url(r'^project/(?P<project_id>\d+)/github/commit$', github_push, name='github_push'),
    url(r'^project/(?P<project_id>\d+)/github/pull$', github_pull, name='github_pull'),
    url(r'^project/(?P<project_id>\d+)/github/push_hook$', github_hook, name='github_hook'),
    url(r'^project/(?P<project_id>\d+)/status\.png$', build_status, name='build_status'),
    url(r'^project/(?P<project_id>\d+)/autocomplete/init', init_autocomplete, name='init_autocomplete'),
    url(r'emulator/launch', launch_emulator, name='launch_emulator'),
    url(r'emulator/config', qemu_config, name='qemu_config'),
    url(r'emulator/(?P<emulator_id>[0-9a-f-]{32,36})/mobile_token', generate_phone_token,  name='qemu_mobile_token'),
    url(r'emulator/token/(?P<token>\d{6})', handle_phone_token,  name='qemu_mobile_token'),
    url(r'emulator/token/?', enter_phone_token,  name='qemu_mobile_token'),
    url(r'^task/(?P<task_id>[0-9a-f-]{32,36})', check_task, name='check_task'),
    url(r'^shortlink$', get_shortlink, name='get_shortlink'),
    url(r'^settings$', settings_page, name='settings'),
    url(r'^settings/github/start$', start_github_auth, name='start_github_auth'),
    url(r'^settings/github/callback$', complete_github_auth, name='complete_github_auth'),
    url(r'^settings/github/unlink$', remove_github_auth, name='remove_github_auth'),
    url(r'^import/zip', import_zip, name='import_zip'),
    url(r'^import/github', import_github, name='import_github'),
    url(r'^import/gist', do_import_gist, name='import_gist'),
    url(r'^transition/accept', transition_accept, name='transition_accept'),
    url(r'^transition/export', transition_export, name='transition_export'),
    url(r'^transition/delete', transition_delete, name='transition_delete'),
    url(r'^packages/search', npm_search, name='package_search'),
    url(r'^packages/info', npm_info, name='package_info'),
    url(r'^ping_phone$', ping_phone),
    url(r'^check_phone/(?P<request_id>[0-9a-f-]+)$', check_phone),
    url(r'^update_phone$', update_phone),
    url(r'^list_phones$', list_phones),
    url(r'^whats_new', whats_new, name='whats_new'),
    url(r'^gist/(?P<gist_id>[0-9a-f]+)$', import_gist),
    url(r'^heartbeat$', heartbeat),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', name='jsi18n'),
)

cloudpebble/qr/urls.py
from django.conf.urls import patterns, url

from qr import views

urlpatterns = patterns(
    '',
    url('$^', views.render, name='render')
)

cloudpebble/ide/models/dependency.py
import re

from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from ide.models.meta import IdeModel


def validate_dependency_version(value):
    if hasattr(settings, 'LOCAL_DEPENDENCY_OVERRIDE'):
        return
    # Disallow paths as versions
    if re.match(r'^file:|(\.*|~)/', value):
        raise ValidationError(_("Local path dependencies are not allowed"))


class Dependency(IdeModel):
    project = models.ForeignKey('Project', related_name='dependencies')
    name = models.CharField(max_length=100)
    version = models.CharField(max_length=2000, validators=[validate_dependency_version])

    class Meta(IdeModel.Meta):
        unique_together = (('project', 'name'),)

cloudpebble/ide/models/meta.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

class IdeModel(models.Model):
    class Meta:
        abstract = True
        app_label = "ide"


@receiver(pre_save)
def pre_save_full_clean_handler(sender, instance, *args, **kwargs):
    """ Force IdeModels to call full_clean before save """
    if isinstance(instance, IdeModel):
        instance.full_clean()

cloudpebble/ide/models/user.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import pgettext_lazy

from ide.models.meta import IdeModel
from ide.utils.whatsnew import count_things

__author__ = 'katharine'


class UserSettings(IdeModel):
    user = models.OneToOneField(User, primary_key=True)

    AUTOCOMPLETE_ALWAYS = 1
    AUTOCOMPLETE_EXPLICIT = 2
    AUTOCOMPLETE_NEVER = 3
    AUTOCOMPLETE_CHOICES = (
        (AUTOCOMPLETE_ALWAYS, _('As-you-type')),
        (AUTOCOMPLETE_EXPLICIT, _('When pressing Ctrl-Space')),
        (AUTOCOMPLETE_NEVER, _('Never'))
    )

    KEYBIND_STANDARD = 'default'
    KEYBIND_VIM = 'vim'
    KEYBIND_EMACS = 'emacs'
    KEYBIND_CHOICES = (
        (KEYBIND_STANDARD, _('Standard')),
        (KEYBIND_VIM, _('vim-like')),
        (KEYBIND_EMACS, _('emacs-like')),
    )

    THEME_CHOICES = (
        ('cloudpebble', 'CloudPebble'),
        ('monokai', 'Monokai (Sublime Text)'),
        ('blackboard', 'Blackboard (TextMate)'),
        ('eclipse', 'Eclipse'),
        ('solarized light', 'Solarized (light)'),
        ('solarized dark', 'Solarized (dark)'),
    )

    USE_SPACES_CHOICES = (
        (True, _('Using spaces')),
        (False, _('Using tabs')),
    )

    def __unicode__(self):
        return self.user.name

    autocomplete = models.IntegerField(choices=AUTOCOMPLETE_CHOICES, verbose_name=_("Autocompletion"), default=AUTOCOMPLETE_ALWAYS)
    keybinds = models.CharField(max_length=20, verbose_name=_("Keybinds"), choices=KEYBIND_CHOICES, default=KEYBIND_STANDARD)
    theme = models.CharField(max_length=50, verbose_name=_("Theme"), choices=THEME_CHOICES, default='cloudpebble')
    use_spaces = models.BooleanField(default=True, verbose_name=pgettext_lazy("number of spaces", u"Indents"), choices=USE_SPACES_CHOICES)
    tab_width = models.PositiveSmallIntegerField(default=2, verbose_name=_("Tab width"))

    # Used for the Pebble ownership transition, when it was set to False.
    accepted_terms = models.BooleanField(default=True)

    # What "what's new" prompt have they seen?
    whats_new = models.PositiveIntegerField(default=count_things)

User.settings = property(lambda self: UserSettings.objects.get_or_create(user=self)[0])


class UserGithub(IdeModel):
    user = models.OneToOneField(User, primary_key=True, related_name='github')
    token = models.CharField(max_length=50, null=True, blank=True)
    nonce = models.CharField(max_length=36, null=True, blank=True)
    username = models.CharField(max_length=50, null=True, blank=True)
    avatar = models.CharField(max_length=255, null=True, blank=True)

cloudpebble/ide/forms.py
from django.forms import ModelForm, Select

from ide.models.user import UserSettings


class SettingsForm(ModelForm):
    class Meta:
        model = UserSettings
        exclude = ('user', 'accepted_terms', 'whats_new')
        widgets = {
            'use_spaces': Select
        }

cloudpebble/ide/views/index.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_safe
from ide.models.project import Project, TemplateProject
from utils.td_helper import send_td_event

__author__ = 'katharine'


@require_safe
@login_required
@ensure_csrf_cookie
def index(request, github_account=None, github_project=None):
    user = request.user
    my_projects = Project.objects.filter(owner=user).order_by('-last_modified')
    if not user.settings.accepted_terms:
        # Screw it.
        # user_settings = user.settings
        # user_settings.accepted_terms = True
        # user_settings.save()

        return render(request, 'ide/new-owner.html', {
            'my_projects': my_projects
        })
    elif settings.SOCIAL_AUTH_PEBBLE_REQUIRED and user.social_auth.filter(provider='pebble').count() == 0:
        return render(request, 'registration/merge_account.html')
    else:
        send_td_event('cloudpebble_project_list', request=request)
        return render(request, 'ide/index.html', {
            'my_projects': my_projects,
            'sdk_templates': TemplateProject.objects.filter(template_kind=TemplateProject.KIND_TEMPLATE),
            'demo_templates': TemplateProject.objects.filter(template_kind=TemplateProject.KIND_SDK_DEMO),
            'default_template_id': settings.DEFAULT_TEMPLATE,
            'user': user,
        })

cloudpebble/ide/views/project.py
import json
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt
from django.views.decorators.http import require_safe, require_POST
from ide.models.build import BuildResult
from ide.models.project import Project
from ide.tasks.git import hooked_commit
from ide.utils import generate_half_uuid
from utils.td_helper import send_td_event
from ide.utils.regexes import regexes

__author__ = 'katharine'


@require_safe
@login_required
@ensure_csrf_cookie
def view_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id, owner=request.user)
    if project.app_uuid is None:
        project.app_uuid = generate_half_uuid()
    if project.app_company_name is None:
        project.app_company_name = request.user.username
    if project.app_short_name is None:
        project.app_short_name = project.name
    if project.app_long_name is None:
        project.app_long_name = project.app_short_name
    if project.app_version_label is None:
        project.app_version_label = '1.0'
    app_keys = project.get_parsed_appkeys()

    send_td_event('cloudpebble_open_project', request=request, project=project)
    try:
        token = request.user.social_auth.get(provider='pebble').extra_data['access_token']
    except:
        token = ''
    return render(request, 'ide/project.html', {
        'project': project,
        'app_keys': app_keys,
        'font_css': settings.TYPOGRAPHY_CSS,
        'libpebble_proxy': json.dumps(settings.LIBPEBBLE_PROXY),
        'token': token,
        'phone_shorturl': settings.PHONE_SHORTURL,
        'supported_platforms': project.supported_platforms,
        'regexes': regexes,
        'regexes_json': json.dumps(regexes.regex_dictionary)
    })


@csrf_exempt
@require_POST
def github_hook(request, project_id):
    hook_uuid = request.GET['key']
    project = get_object_or_404(Project, pk=project_id, github_hook_uuid=hook_uuid)

    push_info = json.loads(request.POST['payload'])
    if push_info['ref'] == 'refs/heads/%s' % (project.github_branch or push_info['repository']['master_branch']):
        hooked_commit.delay(project_id, push_info['after'])

    return HttpResponse('ok')


@require_safe
def build_status(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    try:
        last_build = BuildResult.objects.order_by('-id').filter(~Q(state=BuildResult.STATE_WAITING), project=project)[0]
    except IndexError:
        return HttpResponseRedirect(settings.STATIC_URL + '/ide/img/status/error.png')
    if last_build.state == BuildResult.STATE_SUCCEEDED:
        return HttpResponseRedirect(settings.STATIC_URL + '/ide/img/status/passing.png')
    else:
        return HttpResponseRedirect(settings.STATIC_URL + '/ide/img/status/failing.png')


@require_safe
@login_required
@ensure_csrf_cookie
def import_gist(request, gist_id):
    send_td_event('cloudpebble_gist_landing', data={'data': {'gist_id': gist_id}}, request=request)
    return render(request, 'ide/gist-import.html', {
        'gist_id': gist_id,
        'blurb': request.GET.get('blurb', None)
    })


def qemu_config(request):
    return render(request, 'ide/qemu-config.html')


def enter_phone_token(request):
    return render(request, 'ide/qemu-enter-token.html')

cloudpebble/ide/templates/ide/gist-import.html
{% extends "common/base-narrow.html" %}
{% load staticfiles %}
{% load i18n %}
{% block narrowcontent %}
<div class="well" style="text-align: center;">
    <p style="margin-bottom:20px;">{% trans "You are going to create a project based on a template." %}</p>
    {% if blurb %}
    <p>{{ blurb }}</p>
    <hr>
    {% endif %}
    <p><button class="btn btn-primary btn-large" id="import-btn" style="width: 200px;">{% trans "Create Project" %}</button></p>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
var GIST_ID = "{{ gist_id | escapejs }}";
</script>
<script src="{% static 'ide/js/csrf.js' %}" type="text/javascript"></script>
<script src="{% static 'ide/js/gist_import.js' %}" type="text/javascript"></script>
<script src="/ide/jsi18n/"></script>
{% endblock %}

cloudpebble/ide/templates/ide/new-owner.html
{% extends "common/base-narrow.html" %}
{% load staticfiles %}
{% block narrowcontent %}
    <style>
    p {
        padding: 5px;
    }
    </style>
<div>
    <h1 style="text-align: center;">CloudPebble is now sponsored by Pebble!</h1>
    <div class="well" style="text-align: center;">
        <p>Your account and projects are as you left them, and you can continue as usual:</p>
        <p><button class="btn btn-primary" id="btn-accept" style="width: 250px;">Accept and Continue</button></p>
        <hr>
        <p>If you object to Pebble running CloudPebble, you can export your data and delete your account.</p>
        <p><button class="btn" id="btn-export" style="width: 200px;">Export all projects</button> <button class="btn btn-danger" id="btn-delete" style="width: 200px;">Delete account</button></p>
        <p>Note that deleting your account is permanent and irreversible. Be sure you export your data first!</p>
    </div>
</div>
{% endblock %}

{% block modals %}
<div id="export-progress" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <h3>Exporting…</h3>
    </div>
    <div class="model-body" style="text-align: center;">
        <div id="export-pending-body">
            <div>
                <div id="export-progress-text" style="color: white;">
                    <img src="{% static 'ide/img/zip.png' %}" style="height: 200px; width: 200px; margin-top: 10px;">
                    <div class="progress active">
                        <div class="bar" style="width: 100%;"></div>
                    </div>
                    <p>We're just getting that packaged up for you.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal boolean confirmation prompt -->
<div id="modal-warning-prompt" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <h3 id="modal-warning-prompt-title">Modal header</h3>
    </div>
    <div class="modal-body" style="text-align: center;">
        <p id="modal-warning-prompt-warning">Modal warning</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal">Cancel</button>
        <button class="btn btn-danger" id="modal-warning-prompt-button">Continue</button>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'ide/js/csrf.js' %}" type="text/javascript"></script>
<script src="{% static 'ide/js/new_owner.js' %}" type="text/javascript"></script>
{% endblock %}

cloudpebble/ide/templates/ide/qemu-config.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <script>
        var data = location.search.substr(1);
        console.log(data);
        window.addEventListener('message', function(e) {
            e.source.postMessage(data, '*');
        }, false);
    </script>
</head>
<body>
almost done...
</body>
</html>

cloudpebble/ide/templates/ide/qemu-enter-token.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block head %}
<meta name="viewport" content="width=device-width, user-scalable=no" />
<link rel="stylesheet" type="text/css" href="{% static 'ide/css/mobile.css' %}">
<script type="text/javascript">
window.addEventListener('load', function() {
    console.log('hi');
    function doTheThing() {
        var input = $('#code-input');
        console.log(input);
        if (input.val().length == 6) {
            $('#go-btn').removeAttr('disabled');
        } else {
            $('#go-btn').attr('disabled', 'disabled');
        }
    }
    $('#code-input').on('input', doTheThing);
    $('form').submit(function(e) {
        e.preventDefault();
        location.href = '/ide/emulator/token/' + $('#code-input').val();
    });
    doTheThing();
    $('#code-input').focus();
});
</script>
{% endblock %}
{% block content %}
    <h1 class="cloudpebble-logo">
        <span class="cloudpebble-logo-cloud">Cloud</span><span class="cloudpebble-logo-pebble">Pebble</span>
    </h1>
    <div class="content">
        <!-- I still don't know how to vertically centre things with CSS. -->
        <h2>Enter code</h2>
        <form>
            <input id="code-input" type="tel" pattern="\d*" maxlength="6">
            <p><button class="btn btn-primary" id="go-btn" disabled>Go</button></p>
        </form>
        {% if failed %}
        <div class="well alert alert-error">
            <p>That token wasn't valid. Please try again.</p>
        </div>
        {% endif %}
    </div>
{% endblock %}

cloudpebble/ide/templates/ide/settings.html
{% extends "common/base-narrow.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'ide/css/settings.css' %}">
{% endblock %}

{% block headercontent %}
<ul class="nav-pills">
    <li><a href="{% url 'ide:index' %}" class="btn">{% trans 'Projects' %}</a></li>
    <li><a class="active btn">{% trans 'Settings' %}</a></li>
    <li><a href="{% url 'logout' %}" class="btn">{% trans 'Sign out' %}</a></li>
</ul>
{% endblock %}

{% block narrowcontent %}
<div class="settings-container">
    <div class="editor-settings">
        <h2 class="section-heading">{% trans 'Editor settings' %}</h2>
        <div class="well">
            <form method="post" class="form-horizontal" id="user-settings-form">
                {% if saved %}
                    <div class="well alert alert-success">{% trans 'Settings saved!' %}</div>
                {% endif %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                <div class="control-group">
                    <label for="id_{{field.html_name}}">{{field.label}}</label>
                    <div class="controls">
                        {{ field }}
                        <span class="help-block hide"></span>
                    </div>
                </div>
                {% endfor %}
                <div class="form-actions">
                    <input type="reset" class="btn" value="{% trans 'Reset' %}">
                </div>
            </form>
        </div>
    </div>
    <div class="github-settings">
        <h2 class="section-heading">{% trans 'GitHub Integration' %}</h2>
        <div class="well">
            <form action="{% url 'ide:remove_github_auth' %}" method="post" id="unlink-form">{%csrf_token%}</form>
            {% if github and github.token %}
            <img src="{{ github.avatar }}" class="github-avatar">
            <h2 class="github-username">{{ github.username }}</h2>
            <div class="github-options">
                <p>
                    <form method="post" action="{% url 'ide:start_github_auth' %}">
                        <input type="submit" class="btn btn-primary" value="{% trans 'Re-authenticate' %}">
                        {% csrf_token %}
                    </form>
                </p>
                <p>
                    <form method="post" action="{% url 'ide:remove_github_auth' %}">
                        <input type="submit" class="btn btn-primary" value="{% trans 'Unlink account' %}">
                        {% csrf_token %}
                    </form>
                </p>
                {% else %}
                <p>
                    <form method="post" action="{% url 'ide:start_github_auth' %}">
                        <input type="submit" class="btn btn-primary" value="{% trans 'Link your GitHub account' %}">
                        {% csrf_token %}
                    </form>
                </p>
                {% endif %}
                <hr>
                <p>{% trans 'Connecting your GitHub account enables you to connect your projects to GitHub repositories.' %}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    $(function() {
        jquery_csrf_setup();

        // Warn about emacs kinda sucking.
        $('#id_keybinds').change(function() {
            if($(this).val() == 'emacs') {
                $(this)
                    .siblings('.help-block')
                    .text("Note: the emacs mapping is limited, and will not work properly in some browsers (e.g. Chrome) that prevent using certain keys.")
                    .removeClass('hide')
            } else {
                $(this).siblings('.help-block').addClass('hide');
            }
        });

        $('#unlink-btn').click(function(e) {
            e.preventDefault();
            $('#unlink-form').submit();
        });

        var save = function() {
            return Ajax.Ajax({
                type: "POST",
                url: "settings",
                data: $("#user-settings-form").serialize() // serializes the form's elements.
            });
        };

        make_live_settings_form({
            save_function: save,
            form: $("#user-settings-form")
        }).init();

        $("#user-settings-form").submit(function(e) {
            e.preventDefault();
            return false;
        });
    });
</script>
<script src="{% static 'ide/js/live_settings_form.js' %}" type="text/javascript"></script>
<script src="{% static 'ide/js/csrf.js' %}" type="text/javascript"></script>
{% endblock %}